// DO NOT EDIT THIS FILE MANUALLY. IT IS GENERATED BY scripts/generate_bang_operator.py
use syntax::syntax_kind::SyntaxKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BangOperatorMetadata {
    pub name: &'static str,
    pub signature: &'static str,
    pub needs_type_annotation: bool,
    pub min_args: usize,
    pub max_args: Option<usize>,
    pub syntax_kind: SyntaxKind,
    pub signature_params: &'static [BangSignatureParamMetadata],
    pub documentation: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BangSignatureParamMetadata {
    pub name: &'static str,
    pub optional: bool,
    pub label_start: usize,
    pub label_end: usize,
}

pub fn get_metadata_for_syntax_kind(kind: SyntaxKind) -> Option<&'static BangOperatorMetadata> {
    OPS.iter().find(|meta| meta.syntax_kind == kind)
}

pub const OPS: &[BangOperatorMetadata] = &[
    BangOperatorMetadata {
        name: "add",
        signature: r#"!add(a, b, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XAdd,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator adds *a*, *b*, etc., and produces the sum."#,
    },
    BangOperatorMetadata {
        name: "and",
        signature: r#"!and(a, b, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XAnd,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator does a bitwise AND on *a*, *b*, etc., and produces the
result. A logical AND can be performed if all the arguments are either
0 or 1. This operator is short-circuit to 0 when the left-most operand
is 0."#,
    },
    BangOperatorMetadata {
        name: "cast",
        signature: r#"!cast<type>(a)"#,
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XCast,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 12, label_end: 13 }],
        documentation: r#"This operator performs a cast on *a* and produces the result.
If *a* is not a string, then a straightforward cast is performed, say
between an `int` and a `bit`, or between record types. This allows
casting a record to a class. If a record is cast to `string`, the
record's name is produced.

If *a* is a string, then it is treated as a record name and looked up in
the list of all defined records. The resulting record is expected to be of
the specified *type*.

For example, if `!cast<` *type* `>(` *name* `)`
appears in a multiclass definition, or in a
class instantiated inside a multiclass definition, and the *name* does not
reference any template arguments of the multiclass, then a record by
that name must have been instantiated earlier
in the source file. If *name* does reference
a template argument, then the lookup is delayed until `defm` statements
instantiating the multiclass (or later, if the defm occurs in another
multiclass and template arguments of the inner multiclass that are
referenced by *name* are substituted by values that themselves contain
references to template arguments of the outer multiclass).

If the type of *a* does not match *type*, TableGen raises an error."#,
    },
    BangOperatorMetadata {
        name: "concat",
        signature: r#"!con(a, b, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XCon,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator concatenates the DAG nodes *a*, *b*, etc. Their operations
must equal.

`!con((op a1:$name1, a2:$name2), (op b1:$name3))`

results in the DAG node `(op a1:$name1, a2:$name2, b1:$name3)`."#,
    },
    BangOperatorMetadata {
        name: "cond",
        signature: r#"!cond(cond1:val1, cond2:val2, ..., condn:valn)"#,
        needs_type_annotation: false,
        min_args: 6,
        max_args: None,
        syntax_kind: SyntaxKind::XCond,
        signature_params: &[BangSignatureParamMetadata { name: "cond1", optional: false, label_start: 6, label_end: 11 }, BangSignatureParamMetadata { name: "val1", optional: false, label_start: 12, label_end: 16 }, BangSignatureParamMetadata { name: "cond2", optional: false, label_start: 18, label_end: 23 }, BangSignatureParamMetadata { name: "val2", optional: false, label_start: 24, label_end: 28 }, BangSignatureParamMetadata { name: "condn", optional: false, label_start: 35, label_end: 40 }, BangSignatureParamMetadata { name: "valn", optional: false, label_start: 41, label_end: 45 }],
        documentation: r#"This operator tests *cond1* and returns *val1* if the result is true.
If false, the operator tests *cond2* and returns *val2* if the result is
true. And so forth. An error is reported if no conditions are true.

This example produces the sign word for an integer:

```
!cond(!lt(x, 0) : "negative", !eq(x, 0) : "zero", true : "positive")
```"#,
    },
    BangOperatorMetadata {
        name: "dag",
        signature: r#"!dag(op, arguments, names)"#,
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XDag,
        signature_params: &[BangSignatureParamMetadata { name: "op", optional: false, label_start: 5, label_end: 7 }, BangSignatureParamMetadata { name: "arguments", optional: false, label_start: 9, label_end: 18 }, BangSignatureParamMetadata { name: "names", optional: false, label_start: 20, label_end: 25 }],
        documentation: r#"This operator creates a DAG node with the given operator and
arguments. The *arguments* and *names* arguments must be lists
of equal length or uninitialized (`?`). The *names* argument
must be of type `list<string>`.

Due to limitations of the type system, *arguments* must be a list of items
of a common type. In practice, this means that they should either have the
same type or be records with a common parent class. Mixing `dag` and
non-`dag` items is not possible. However, `?` can be used.

Example: `!dag(op, [a1, a2, ?], ["name1", "name2", "name3"])` results in
`(op a1-value:$name1, a2-value:$name2, ?:$name3)`."#,
    },
    BangOperatorMetadata {
        name: "div",
        signature: r#"!div(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XDiv,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator performs signed division of *a* by *b*, and produces the quotient.
Division by 0 produces an error. Division of INT64_MIN by -1 produces an error."#,
    },
    BangOperatorMetadata {
        name: "empty",
        signature: r#"!empty(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XEmpty,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator produces 1 if the string, list, or DAG *a* is empty; 0 otherwise.
A dag is empty if it has no arguments; the operator does not count."#,
    },
    BangOperatorMetadata {
        name: "eq",
        signature: r#"!eq(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XEq,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 4, label_end: 5 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator produces 1 if *a* is equal to *b*; 0 otherwise.
The arguments must be `bit`, `bits`, `int`, `string`, or
record values. Use `!cast<string>` to compare other types of objects."#,
    },
    BangOperatorMetadata {
        name: "exists",
        signature: r#"!exists<type>(name)"#,
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XExists,
        signature_params: &[BangSignatureParamMetadata { name: "name", optional: false, label_start: 14, label_end: 18 }],
        documentation: r#"This operator produces 1 if a record of the given *type* whose name is *name*
exists; 0 otherwise. *name* should be of type *string*."#,
    },
    BangOperatorMetadata {
        name: "filter",
        signature: r#"!filter(var, list, predicate)"#,
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XFilter,
        signature_params: &[BangSignatureParamMetadata { name: "var", optional: false, label_start: 8, label_end: 11 }, BangSignatureParamMetadata { name: "list", optional: false, label_start: 13, label_end: 17 }, BangSignatureParamMetadata { name: "predicate", optional: false, label_start: 19, label_end: 28 }],
        documentation: r#"This operator creates a new `list` by filtering the elements in
*list*. To perform the filtering, TableGen binds the variable *var* to each
element and then evaluates the *predicate* expression, which presumably
refers to *var*. The predicate must
produce a boolean value (`bit`, `bits`, or `int`). The value is
interpreted as with `!if`:
if the value is 0, the element is not included in the new list. If the value
is anything else, the element is included."#,
    },
    BangOperatorMetadata {
        name: "find",
        signature: r#"!find(string1, string2[, start])"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XFind,
        signature_params: &[BangSignatureParamMetadata { name: "string1", optional: false, label_start: 6, label_end: 13 }, BangSignatureParamMetadata { name: "string2", optional: false, label_start: 15, label_end: 22 }, BangSignatureParamMetadata { name: "start", optional: true, label_start: 25, label_end: 30 }],
        documentation: r#"This operator searches for *string2* in *string1* and produces its
position. The starting position of the search may be specified by *start*,
which can range between 0 and the length of *string1*; the default is 0.
If the string is not found, the result is -1."#,
    },
    BangOperatorMetadata {
        name: "foldl",
        signature: r#"!foldl(init, list, acc, var, expr)"#,
        needs_type_annotation: false,
        min_args: 5,
        max_args: Some(5),
        syntax_kind: SyntaxKind::XFoldl,
        signature_params: &[BangSignatureParamMetadata { name: "init", optional: false, label_start: 7, label_end: 11 }, BangSignatureParamMetadata { name: "list", optional: false, label_start: 13, label_end: 17 }, BangSignatureParamMetadata { name: "acc", optional: false, label_start: 19, label_end: 22 }, BangSignatureParamMetadata { name: "var", optional: false, label_start: 24, label_end: 27 }, BangSignatureParamMetadata { name: "expr", optional: false, label_start: 29, label_end: 33 }],
        documentation: r#"This operator performs a left-fold over the items in *list*. The
variable *acc* acts as the accumulator and is initialized to *init*.
The variable *var* is bound to each element in the *list*. The
expression is evaluated for each element and presumably uses *acc* and
*var* to calculate the accumulated value, which `!foldl` stores back in
*acc*. The type of *acc* is the same as *init*; the type of *var* is the
same as the elements of *list*; *expr* must have the same type as *init*.

The following example computes the total of the `Number` field in the
list of records in `RecList`:

```
int x = !foldl(0, RecList, total, rec, !add(total, rec.Number));
```
If your goal is to filter the list and produce a new list that includes only
some of the elements, see `!filter`."#,
    },
    BangOperatorMetadata {
        name: "foreach",
        signature: r#"!foreach(var, sequence, expr)"#,
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XForEach,
        signature_params: &[BangSignatureParamMetadata { name: "var", optional: false, label_start: 9, label_end: 12 }, BangSignatureParamMetadata { name: "sequence", optional: false, label_start: 14, label_end: 22 }, BangSignatureParamMetadata { name: "expr", optional: false, label_start: 24, label_end: 28 }],
        documentation: r#"This operator creates a new `list`/`dag` in which each element is a
function of the corresponding element in the *sequence* `list`/`dag`.
To perform the function, TableGen binds the variable *var* to an element
and then evaluates the expression. The expression presumably refers
to the variable *var* and calculates the result value.

If you simply want to create a list of a certain length containing
the same value repeated multiple times, see `!listsplat`."#,
    },
    BangOperatorMetadata {
        name: "ge",
        signature: r#"!ge(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGe,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 4, label_end: 5 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator produces 1 if *a* is greater than or equal to *b*; 0 otherwise.
The arguments must be `bit`, `bits`, `int`, or `string` values."#,
    },
    BangOperatorMetadata {
        name: "getdagarg",
        signature: r#"!getdagarg<type>(dag, key)"#,
        needs_type_annotation: true,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGetDagArg,
        signature_params: &[BangSignatureParamMetadata { name: "dag", optional: false, label_start: 17, label_end: 20 }, BangSignatureParamMetadata { name: "key", optional: false, label_start: 22, label_end: 25 }],
        documentation: r#"This operator retrieves the argument from the given *dag* node by the
specified *key*, which is either an integer index or a string name. If that
argument is not convertible to the specified *type*, `?` is returned."#,
    },
    BangOperatorMetadata {
        name: "getdagname",
        signature: r#"!getdagname(dag, index)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGetDagName,
        signature_params: &[BangSignatureParamMetadata { name: "dag", optional: false, label_start: 12, label_end: 15 }, BangSignatureParamMetadata { name: "index", optional: false, label_start: 17, label_end: 22 }],
        documentation: r#"This operator retrieves the argument name from the given *dag* node by the
specified *index*. If that argument has no name associated, `?` is
returned."#,
    },
    BangOperatorMetadata {
        name: "getdagop",
        signature: r#"!getdagop(dag)"#,
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XGetDagOp,
        signature_params: &[BangSignatureParamMetadata { name: "dag", optional: false, label_start: 10, label_end: 13 }],
        documentation: r#"This operator produces the operator of the given *dag* node.
Example: `!getdagop((foo 1, 2))` results in `foo`. Recall that
DAG operators are always records.

The result of `!getdagop` can be used directly in a context where
any record class at all is acceptable (typically placing it into
another dag value). But in other contexts, it must be explicitly
cast to a particular class. The `<` *type* `>` syntax is
provided to make this easy.

For example, to assign the result to a value of type `BaseClass`, you
could write either of these:

```
BaseClass b = !getdagop<BaseClass>(someDag);
BaseClass b = !cast<BaseClass>(!getdagop(someDag));
```
But to create a new DAG node that reuses the operator from another, no
cast is necessary:

```
dag d = !dag(!getdagop(someDag), args, names);
```"#,
    },
    BangOperatorMetadata {
        name: "gt",
        signature: r#"!gt(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGt,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 4, label_end: 5 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator produces 1 if *a* is greater than *b*; 0 otherwise.
The arguments must be `bit`, `bits`, `int`, or `string` values."#,
    },
    BangOperatorMetadata {
        name: "head",
        signature: r#"!head(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XHead,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 6, label_end: 7 }],
        documentation: r#"This operator produces the zeroth element of the list *a*.
(See also `!tail`.)"#,
    },
    BangOperatorMetadata {
        name: "if",
        signature: r#"!if(test, then, else)"#,
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XIf,
        signature_params: &[BangSignatureParamMetadata { name: "test", optional: false, label_start: 4, label_end: 8 }, BangSignatureParamMetadata { name: "then", optional: false, label_start: 10, label_end: 14 }, BangSignatureParamMetadata { name: "else", optional: false, label_start: 16, label_end: 20 }],
        documentation: r#"This operator evaluates the *test*, which must produce a `bit` or
`int`. If the result is not 0, the *then* expression is produced; otherwise
the *else* expression is produced."#,
    },
    BangOperatorMetadata {
        name: "initialized",
        signature: r#"!initialized(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XInitialized,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 13, label_end: 14 }],
        documentation: r#"This operator produces 1 if *a* is not the uninitialized value (`?`) and 0
otherwise."#,
    },
    BangOperatorMetadata {
        name: "instances",
        signature: r#"!instances<type>([regex])"#,
        needs_type_annotation: true,
        min_args: 0,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XInstances,
        signature_params: &[BangSignatureParamMetadata { name: "regex", optional: true, label_start: 18, label_end: 23 }],
        documentation: r#"This operator produces a list of records whose type is *type*. If *regex*
is provided, only records whose name matches the regular expression *regex*
will be included. The format of *regex* is ERE (Extended POSIX Regular
Expressions).

If `!instances` is in a class/multiclass/foreach, only these records of
*type* that have been instantiated will be considered."#,
    },
    BangOperatorMetadata {
        name: "interleave",
        signature: r#"!interleave(list, delim)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XInterleave,
        signature_params: &[BangSignatureParamMetadata { name: "list", optional: false, label_start: 12, label_end: 16 }, BangSignatureParamMetadata { name: "delim", optional: false, label_start: 18, label_end: 23 }],
        documentation: r#"This operator concatenates the items in the *list*, interleaving the
*delim* string between each pair, and produces the resulting string.
The list can be a list of string, int, bits, or bit. An empty list
results in an empty string. The delimiter can be the empty string."#,
    },
    BangOperatorMetadata {
        name: "isa",
        signature: r#"!isa<type>(a)"#,
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XIsA,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 11, label_end: 12 }],
        documentation: r#"This operator produces 1 if the type of *a* is a subtype of the given *type*; 0
otherwise."#,
    },
    BangOperatorMetadata {
        name: "le",
        signature: r#"!le(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XLe,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 4, label_end: 5 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator produces 1 if *a* is less than or equal to *b*; 0 otherwise.
The arguments must be `bit`, `bits`, `int`, or `string` values."#,
    },
    BangOperatorMetadata {
        name: "listconcat",
        signature: r#"!listconcat(list1, list2, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XListConcat,
        signature_params: &[BangSignatureParamMetadata { name: "list1", optional: false, label_start: 12, label_end: 17 }, BangSignatureParamMetadata { name: "list2", optional: false, label_start: 19, label_end: 24 }],
        documentation: r#"This operator concatenates the list arguments *list1*, *list2*, etc., and
produces the resulting list. The lists must have the same element type."#,
    },
    BangOperatorMetadata {
        name: "listflatten",
        signature: r#"!listflatten(list)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XListFlatten,
        signature_params: &[BangSignatureParamMetadata { name: "list", optional: false, label_start: 13, label_end: 17 }],
        documentation: r#"This operator flattens a list of lists *list* and produces a list with all
elements of the constituent lists concatenated. If *list* is of type
`list<list<X>>` the resulting list is of type `list<X>`. If *list*'s
element type is not a list, the result is *list* itself."#,
    },
    BangOperatorMetadata {
        name: "listremove",
        signature: r#"!listremove(list1, list2)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XListRemove,
        signature_params: &[BangSignatureParamMetadata { name: "list1", optional: false, label_start: 12, label_end: 17 }, BangSignatureParamMetadata { name: "list2", optional: false, label_start: 19, label_end: 24 }],
        documentation: r#"This operator returns a copy of *list1* removing all elements that also occur in
*list2*. The lists must have the same element type."#,
    },
    BangOperatorMetadata {
        name: "listsplat",
        signature: r#"!listsplat(value, count)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XListSplat,
        signature_params: &[BangSignatureParamMetadata { name: "value", optional: false, label_start: 11, label_end: 16 }, BangSignatureParamMetadata { name: "count", optional: false, label_start: 18, label_end: 23 }],
        documentation: r#"This operator produces a list of length *count* whose elements are all
equal to the *value*. For example, `!listsplat(42, 3)` results in
`[42, 42, 42]`."#,
    },
    BangOperatorMetadata {
        name: "log2",
        signature: r#"!logtwo(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XLog2,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator produces the base 2 log of *a* and produces the integer
result. The log of 0 or a negative number produces an error. This
is a flooring operation."#,
    },
    BangOperatorMetadata {
        name: "lt",
        signature: r#"!lt(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XLt,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 4, label_end: 5 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator produces 1 if *a* is less than *b*; 0 otherwise.
The arguments must be `bit`, `bits`, `int`, or `string` values."#,
    },
    BangOperatorMetadata {
        name: "match",
        signature: r#"!match(str, regex)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XMatch,
        signature_params: &[BangSignatureParamMetadata { name: "str", optional: false, label_start: 7, label_end: 10 }, BangSignatureParamMetadata { name: "regex", optional: false, label_start: 12, label_end: 17 }],
        documentation: r#"This operator produces 1 if the *str* matches the regular expression
*regex*. The format of *regex* is ERE (Extended POSIX Regular Expressions)."#,
    },
    BangOperatorMetadata {
        name: "mul",
        signature: r#"!mul(a, b, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XMul,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator multiplies *a*, *b*, etc., and produces the product."#,
    },
    BangOperatorMetadata {
        name: "ne",
        signature: r#"!ne(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XNe,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 4, label_end: 5 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator produces 1 if *a* is not equal to *b*; 0 otherwise.
The arguments must be `bit`, `bits`, `int`, `string`,
or record values. Use `!cast<string>` to compare other types of objects."#,
    },
    BangOperatorMetadata {
        name: "not",
        signature: r#"!not(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XNot,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }],
        documentation: r#"This operator performs a logical NOT on *a*, which must be
an integer. The argument 0 results in 1 (true); any other
argument results in 0 (false)."#,
    },
    BangOperatorMetadata {
        name: "or",
        signature: r#"!or(a, b, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XOr,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 4, label_end: 5 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 7, label_end: 8 }],
        documentation: r#"This operator does a bitwise OR on *a*, *b*, etc., and produces the
result. A logical OR can be performed if all the arguments are either
0 or 1. This operator is short-circuit to -1 (all ones) the left-most
operand is -1."#,
    },
    BangOperatorMetadata {
        name: "range",
        signature: r#"!range([start, ]end[, step])"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XRange,
        signature_params: &[BangSignatureParamMetadata { name: "start", optional: true, label_start: 8, label_end: 13 }, BangSignatureParamMetadata { name: "end", optional: false, label_start: 16, label_end: 19 }, BangSignatureParamMetadata { name: "step", optional: true, label_start: 22, label_end: 26 }],
        documentation: r#"This operator produces half-open range sequence `[start : end : step)` as
`list<int>`. *start* is `0` and *step* is `1` by default. *step* can
be negative and cannot be 0. If *start* `<` *end* and *step* is negative,
or *start* `>` *end* and *step* is positive, the result is an empty list
`[]<list<int>>`.

For example:

* `!range(4)` is equivalent to `!range(0, 4, 1)` and the result is
  `[0, 1, 2, 3]`.
* `!range(1, 4)` is equivalent to `!range(1, 4, 1)` and the result is
  `[1, 2, 3]`.
* The result of `!range(0, 4, 2)` is `[0, 2]`.
* The results of `!range(0, 4, -1)` and `!range(4, 0, 1)` are empty."#,
    },
    BangOperatorMetadata {
        name: "range",
        signature: r#"!range(list)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XRange,
        signature_params: &[BangSignatureParamMetadata { name: "list", optional: false, label_start: 7, label_end: 11 }],
        documentation: r#"Equivalent to `!range(0, !size(list))`."#,
    },
    BangOperatorMetadata {
        name: "repr",
        signature: r#"!repr(value)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XRepr,
        signature_params: &[BangSignatureParamMetadata { name: "value", optional: false, label_start: 6, label_end: 11 }],
        documentation: r#"Represents *value* as a string. String format for the value is not
guaranteed to be stable. Intended for debugging purposes only."#,
    },
    BangOperatorMetadata {
        name: "setdagarg",
        signature: r#"!setdagarg(dag, key, arg)"#,
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSetDagArg,
        signature_params: &[BangSignatureParamMetadata { name: "dag", optional: false, label_start: 11, label_end: 14 }, BangSignatureParamMetadata { name: "key", optional: false, label_start: 16, label_end: 19 }, BangSignatureParamMetadata { name: "arg", optional: false, label_start: 21, label_end: 24 }],
        documentation: r#"This operator produces a DAG node with the same operator and arguments as
*dag*, but replacing the value of the argument specified by the *key* with
*arg*. That *key* could be either an integer index or a string name."#,
    },
    BangOperatorMetadata {
        name: "setdagname",
        signature: r#"!setdagname(dag, key, name)"#,
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSetDagName,
        signature_params: &[BangSignatureParamMetadata { name: "dag", optional: false, label_start: 12, label_end: 15 }, BangSignatureParamMetadata { name: "key", optional: false, label_start: 17, label_end: 20 }, BangSignatureParamMetadata { name: "name", optional: false, label_start: 22, label_end: 26 }],
        documentation: r#"This operator produces a DAG node with the same operator and arguments as
*dag*, but replacing the name of the argument specified by the *key* with
*name*. That *key* could be either an integer index or a string name."#,
    },
    BangOperatorMetadata {
        name: "setdagop",
        signature: r#"!setdagop(dag, op)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSetDagOp,
        signature_params: &[BangSignatureParamMetadata { name: "dag", optional: false, label_start: 10, label_end: 13 }, BangSignatureParamMetadata { name: "op", optional: false, label_start: 15, label_end: 17 }],
        documentation: r#"This operator produces a DAG node with the same arguments as *dag*, but with its
operator replaced with *op*.

Example: `!setdagop((foo 1, 2), bar)` results in `(bar 1, 2)`."#,
    },
    BangOperatorMetadata {
        name: "shl",
        signature: r#"!shl(a, count)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XShl,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "count", optional: false, label_start: 8, label_end: 13 }],
        documentation: r#"This operator shifts *a* left logically by *count* bits and produces the resulting
value. The operation is performed on a 64-bit integer; the result
is undefined for shift counts outside 0...63."#,
    },
    BangOperatorMetadata {
        name: "size",
        signature: r#"!size(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XSize,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 6, label_end: 7 }],
        documentation: r#"This operator produces the size of the string, list, or dag *a*.
The size of a DAG is the number of arguments; the operator does not count."#,
    },
    BangOperatorMetadata {
        name: "sra",
        signature: r#"!sra(a, count)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSra,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "count", optional: false, label_start: 8, label_end: 13 }],
        documentation: r#"This operator shifts *a* right arithmetically by *count* bits and produces the resulting
value. The operation is performed on a 64-bit integer; the result
is undefined for shift counts outside 0...63."#,
    },
    BangOperatorMetadata {
        name: "srl",
        signature: r#"!srl(a, count)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSrl,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "count", optional: false, label_start: 8, label_end: 13 }],
        documentation: r#"This operator shifts *a* right logically by *count* bits and produces the resulting
value. The operation is performed on a 64-bit integer; the result
is undefined for shift counts outside 0...63."#,
    },
    BangOperatorMetadata {
        name: "strconcat",
        signature: r#"!strconcat(str1, str2, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XStrConcat,
        signature_params: &[BangSignatureParamMetadata { name: "str1", optional: false, label_start: 11, label_end: 15 }, BangSignatureParamMetadata { name: "str2", optional: false, label_start: 17, label_end: 21 }],
        documentation: r#"This operator concatenates the string arguments *str1*, *str2*, etc., and
produces the resulting string."#,
    },
    BangOperatorMetadata {
        name: "sub",
        signature: r#"!sub(a, b)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSub,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator subtracts *b* from *a* and produces the arithmetic difference."#,
    },
    BangOperatorMetadata {
        name: "subst",
        signature: r#"!subst(target, repl, value)"#,
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSubst,
        signature_params: &[BangSignatureParamMetadata { name: "target", optional: false, label_start: 7, label_end: 13 }, BangSignatureParamMetadata { name: "repl", optional: false, label_start: 15, label_end: 19 }, BangSignatureParamMetadata { name: "value", optional: false, label_start: 21, label_end: 26 }],
        documentation: r#"This operator replaces all occurrences of the *target* in the *value* with
the *repl* and produces the resulting value. The *value* can
be a string, in which case substring substitution is performed.

The *value* can be a record name, in which case the operator produces the *repl*
record if the *target* record name equals the *value* record name; otherwise it
produces the *value*."#,
    },
    BangOperatorMetadata {
        name: "substr",
        signature: r#"!substr(string, start[, length])"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSubstr,
        signature_params: &[BangSignatureParamMetadata { name: "string", optional: false, label_start: 8, label_end: 14 }, BangSignatureParamMetadata { name: "start", optional: false, label_start: 16, label_end: 21 }, BangSignatureParamMetadata { name: "length", optional: true, label_start: 24, label_end: 30 }],
        documentation: r#"This operator extracts a substring of the given *string*. The starting
position of the substring is specified by *start*, which can range
between 0 and the length of the string. The length of the substring
is specified by *length*; if not specified, the rest of the string is
extracted. The *start* and *length* arguments must be integers."#,
    },
    BangOperatorMetadata {
        name: "tail",
        signature: r#"!tail(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XTail,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 6, label_end: 7 }],
        documentation: r#"This operator produces a new list with all the elements
of the list *a* except for the zeroth one. (See also `!head`.)"#,
    },
    BangOperatorMetadata {
        name: "tolower",
        signature: r#"!tolower(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XToLower,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 9, label_end: 10 }],
        documentation: r#"This operator converts a string input *a* to lower case."#,
    },
    BangOperatorMetadata {
        name: "toupper",
        signature: r#"!toupper(a)"#,
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XToUpper,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 9, label_end: 10 }],
        documentation: r#"This operator converts a string input *a* to upper case."#,
    },
    BangOperatorMetadata {
        name: "xor",
        signature: r#"!xor(a, b, ...)"#,
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XXor,
        signature_params: &[BangSignatureParamMetadata { name: "a", optional: false, label_start: 5, label_end: 6 }, BangSignatureParamMetadata { name: "b", optional: false, label_start: 8, label_end: 9 }],
        documentation: r#"This operator does a bitwise EXCLUSIVE OR on *a*, *b*, etc., and produces
the result. A logical XOR can be performed if all the arguments are either
0 or 1."#,
    },
];
  
