use syntax::syntax_kind::SyntaxKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BangOperatorMetadata {
    pub name: &'static str,
    pub needs_type_annotation: bool,
    pub min_args: usize,
    pub max_args: Option<usize>,
    pub syntax_kind: SyntaxKind,
}

pub fn get_metadata_for_syntax_kind(kind: SyntaxKind) -> Option<&'static BangOperatorMetadata> {
    OPS.iter().find(|meta| meta.syntax_kind == kind)
}

pub fn get_metadata_for_name(name: &str) -> Option<&'static BangOperatorMetadata> {
    OPS.iter().find(|meta| meta.name == name)
}

pub const OPS: &[BangOperatorMetadata] = &[
    BangOperatorMetadata {
        name: "add",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XAdd,
    },
    BangOperatorMetadata {
        name: "and",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XAnd,
    },
    BangOperatorMetadata {
        name: "cast",
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XCast,
    },
    BangOperatorMetadata {
        name: "concat",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XCon,
    },
    BangOperatorMetadata {
        name: "dag",
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XDag,
    },
    BangOperatorMetadata {
        name: "div",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XDiv,
    },
    BangOperatorMetadata {
        name: "empty",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XEmpty,
    },
    BangOperatorMetadata {
        name: "eq",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XEq,
    },
    BangOperatorMetadata {
        name: "exists",
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XExists,
    },
    BangOperatorMetadata {
        name: "filter",
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XFilter,
    },
    BangOperatorMetadata {
        name: "find",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XFind,
    },
    BangOperatorMetadata {
        name: "foldl",
        needs_type_annotation: false,
        min_args: 5,
        max_args: Some(5),
        syntax_kind: SyntaxKind::XFoldl,
    },
    BangOperatorMetadata {
        name: "foreach",
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XForEach,
    },
    BangOperatorMetadata {
        name: "ge",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGe,
    },
    BangOperatorMetadata {
        name: "getdagarg",
        needs_type_annotation: true,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGetDagArg,
    },
    BangOperatorMetadata {
        name: "getdagname",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGetDagName,
    },
    BangOperatorMetadata {
        name: "getdagop",
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XGetDagOp,
    },
    BangOperatorMetadata {
        name: "gt",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XGt,
    },
    BangOperatorMetadata {
        name: "head",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XHead,
    },
    BangOperatorMetadata {
        name: "if",
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XIf,
    },
    BangOperatorMetadata {
        name: "initialized",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XInitialized,
    },
    BangOperatorMetadata {
        name: "instances",
        needs_type_annotation: true,
        min_args: 0,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XInstances,
    },
    BangOperatorMetadata {
        name: "interleave",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XInterleave,
    },
    BangOperatorMetadata {
        name: "isa",
        needs_type_annotation: true,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XIsA,
    },
    BangOperatorMetadata {
        name: "le",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XLe,
    },
    BangOperatorMetadata {
        name: "listconcat",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XListConcat,
    },
    BangOperatorMetadata {
        name: "listflatten",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XListFlatten,
    },
    BangOperatorMetadata {
        name: "listremove",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XListRemove,
    },
    BangOperatorMetadata {
        name: "listsplat",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XListSplat,
    },
    BangOperatorMetadata {
        name: "log2",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XLog2,
    },
    BangOperatorMetadata {
        name: "lt",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XLt,
    },
    BangOperatorMetadata {
        name: "mul",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XMul,
    },
    BangOperatorMetadata {
        name: "ne",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XNe,
    },
    BangOperatorMetadata {
        name: "not",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XNot,
    },
    BangOperatorMetadata {
        name: "or",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XOr,
    },
    BangOperatorMetadata {
        name: "range",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XRange,
    },
    BangOperatorMetadata {
        name: "repr",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XRepr,
    },
    BangOperatorMetadata {
        name: "setdagarg",
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSetDagArg,
    },
    BangOperatorMetadata {
        name: "setdagname",
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSetDagName,
    },
    BangOperatorMetadata {
        name: "setdagop",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSetDagOp,
    },
    BangOperatorMetadata {
        name: "shl",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XShl,
    },
    BangOperatorMetadata {
        name: "size",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XSize,
    },
    BangOperatorMetadata {
        name: "sra",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSra,
    },
    BangOperatorMetadata {
        name: "srl",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSrl,
    },
    BangOperatorMetadata {
        name: "strconcat",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XStrConcat,
    },
    BangOperatorMetadata {
        name: "sub",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(2),
        syntax_kind: SyntaxKind::XSub,
    },
    BangOperatorMetadata {
        name: "subst",
        needs_type_annotation: false,
        min_args: 3,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSubst,
    },
    BangOperatorMetadata {
        name: "substr",
        needs_type_annotation: false,
        min_args: 2,
        max_args: Some(3),
        syntax_kind: SyntaxKind::XSubstr,
    },
    BangOperatorMetadata {
        name: "tail",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XTail,
    },
    BangOperatorMetadata {
        name: "tolower",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XToLower,
    },
    BangOperatorMetadata {
        name: "toupper",
        needs_type_annotation: false,
        min_args: 1,
        max_args: Some(1),
        syntax_kind: SyntaxKind::XToUpper,
    },
    BangOperatorMetadata {
        name: "xor",
        needs_type_annotation: false,
        min_args: 2,
        max_args: None,
        syntax_kind: SyntaxKind::XXor,
    },
];
