[package]
name = "lsp"
version.workspace = true
edition.workspace = true

[dependencies]
async-lsp = { version = "0.2.0", features = ["tokio"] }
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
