name: Setup LLVM

runs:
  using: composite
  steps:
    - name: Setup LLVM
      shell: bash
      run: |
        llvm_version=$(cat ".github/LLVM_VERSION" | tr -d '\r\n')
        
        base_url="https://github.com/arata-nvm/tablegen-lsp/releases/download/llvm-${llvm_version}"
        filename="LLVM-${llvm_version}-${{ runner.os }}-${{ runner.arch }}.tar.xz"
        
        llvm_prefix="${RUNNER_TEMP}/llvm-download"
        mkdir "$llvm_prefix"
        cd "$llvm_prefix"
        
        curl -LO "${base_url}/${filename}"
        tar -xf "$filename"
        
        llvm_version_suffix=$(echo "$llvm_version" | awk -F. '{print $1"0"}')
        echo "TABLEGEN_${llvm_version_suffix}_PREFIX=${llvm_prefix}" >>$GITHUB_ENV
