[target.x86-64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Ctarget-cpu=native"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Ctarget-cpu=native"]
