name: CI(client)

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/**
      - vscode/**
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
        working-directory: ./vscode
      - run: npm run build
        working-directory: ./vscode

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
        working-directory: ./vscode
      - run: npm run lint:check
        working-directory: ./vscode

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
        working-directory: ./vscode
      - run: npm run format:check
        working-directory: ./vscode
