name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19.1"
      - name: Set env
        run: echo "TABLEGEN_190_PREFIX=${{ env.LLVM_PATH }}" >> $GITHUB_ENV
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
